### PR TITLE
Add ElastiCache to the template

### PR DESCRIPTION
**Pull request by tompizmor**

### CODE REVIEW

**Comment by tompizmor** [comment]
Please do not merge this yet.
We need to publish new WordPress AMIs.

We will update this PR once they are released.

**Comment by agamzn** [comment]
@tompizmor  - while you're here, we'll also need an updated deployment guide and architecture diagram.  @andresbono  has my contact info.

**Comment by andresbono** [comment]
Hi @agamzn, we've just published the AMIs that include the changes for ElastiCache. I'll send you over the updated deployment guide and architecture diagram in the following days; we're also including a section to fine-tune opCache settings.

Keep this PR blocked if you want to keep consistency between the documents and the templates.

**Comment by agamzn** [comment]
@andresbono  - Thanks! I'll leave this open for the time being as an outstanding item.

**Pull request merged**
