### PR TITLE
Update parameters

### PR DESCRIPTION
**Pull request by andresbono**
This PR includes several changes to improve the parameters of the solution:

- Improve descriptions
- Add an explicit parameter to use SSL or not.
- Allow a new optional parameter to provide an AMI for the webserver.

### CODE REVIEW

**Comment by andresbono** [comment]
Please @andrew-glenn, take a look when you have a chance!

**Comment by andresbono** [comment]
@beltran-rubo, @juan131, @rafariossaa review it please.

**Comment by juan131** [comment]
Hi @andrew-glenn 

Do you mean the change in the "AllowedPattern" regex? 

```diff
- "AllowedPattern": "^[0-9a-zA-Z-/]*$",
+ "AllowedPattern": "^[^/][0-9a-zA-Z-/._]*[^/]$",
```

It's just a change to allow QSS3KeyPrefix with "underscores" (sth like: `path/to/my_bucket/`). Appart from that, it excludes include the final "forward slash" so we it requires changes like the one below:

```diff
- "Fn::Sub": "${QSS3KeyPrefix}functions/packages/ACMCert/lambda.zip"
+ "Fn::Sub": "${QSS3KeyPrefix}/functions/packages/ACMCert/lambda.zip"
```

IMHO opinion is more standard to use `${VARIABLE}/a/b/c` rather than `${VARIABLE}a/b/c` and assuming that "$VARIABLE" includes the forward slash.

**Comment by andresbono** [comment]
Hi @andrew-glenn, if you prefer, we can keep the current values of "QSS3KeyPrefix" but we should at least change the description:

> It cannot start or end with forward slash (/) because they are automatically appended

https://github.com/aws-quickstart/quickstart-bitnami-wordpress/pull/33/files#diff-6e4fc83cddfd8ec4e57ded2f433fe4fbL95

What do you think?

**Comment by andrew-glenn** [comment]
@juan131  @andresbono  - I'm fine with the underscores. I don't want to remove the extra forward slash (yet) as I don't want this quickstart to become a one-off from the others in this regard. I'm working on standardizing this across the board, but it's  a WIP. 

I'm happy to approve this if you're ok adding the forward-slash back in. :)

**Comment by andresbono** [comment]
@andrew-glenn, I just reverted the forward-slash changes.

**Comment by andrew-glenn** [comment]
👍

**Pull request merged**
