### PR TITLE
Add x2i instance types to template

### PR DESCRIPTION
**Pull request by marcosbc**
Signed-off-by: Marcos Bjoerkelund <marcosbd@vmware.com>

*Issue #, if available:* N/A

*Description of changes:* Adds new instance types to the template.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by andrew-glenn** [comment]
Please rebase against main. It should include commits that address linting errors.

**Comment by marcosbc** [comment]
Done @andrew-glenn!

**Comment by marcosbc** [comment]
Hi @andrew-glenn, just wanted to follow up on this PR. Let us know if you need anything else from us.

**Pull request merged**
