### PR TITLE
Add support for new instance types: m6a.*, m6i.metal, c6i.*, r6i.* and update AMIs

### PR DESCRIPTION
**Pull request by marcosbc**
*Description of changes:*

This PR adds new instance types that are supported on EC2: `m6a.*`, `m6i.metal`, `c6i.*` and `r6i.*`, and also updates the AMI IDs for the latest version of the web server image.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by marcosbc** [comment]
Hi @andrew-glenn, I just wanted to follow up on this. Please let us know if you are missing anything.

**Comment by andrew-glenn** [comment]
Hi @marcosbc  - I'm working on a PR in parallel to address the linting issues. I expect to have that merged in later today. I'll ask you to re-base at that point so we can test this.

**Comment by marcosbc** [comment]
That's great, thanks for the heads up!

**Comment by andrew-glenn** [comment]
@marcosbc please rebase from `main`. Once complete I can test this then merge. 👍

**Comment by marcosbc** [comment]
Done 👍

**Pull request merged**
